apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: jaeger-4.0.0
    releaseName: jaeger
    valuesFile: values.yaml
    namespace: observability